package feedbackdatos;
// Generated 11-dic-2019 17:06:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.GregorianCalendar;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private int idCoche;
     private String matricula;
     private Float precio;
     private String color;
     private String marca;
     private Date fechaMatriculacion;

    public Coches() {
    }

	
    public Coches(int idCoche, String matricula, Date fechaMatriculacion) {
        this.idCoche = idCoche;
        this.matricula = matricula;
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Coches(int idCoche, String matricula, Float precio, String color, String marca, Date fechaMatriculacion) {
       this.idCoche = idCoche;
       this.matricula = matricula;
       this.precio = precio;
       this.color = color;
       this.marca = marca;
       this.fechaMatriculacion = fechaMatriculacion;
    }
   
    public int getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(int idCoche) {
        this.idCoche = idCoche;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMarca() {
        return this.marca;
    }

    @Override
    public String toString() {
        return "Coches{" + "idCoche=" + idCoche + ", matricula=" + matricula + ", precio=" + precio + ", color=" + color + ", marca=" + marca + ", fechaMatriculacion=" + fechaMatriculacion + '}';
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Date getFechaMatriculacion() {
        return this.fechaMatriculacion;
    }
    
    public void setFechaMatriculacion(Date fechaMatriculacion) {
        this.fechaMatriculacion = fechaMatriculacion;
    }




}


