package feedbackdatos;
// Generated 11-dic-2019 17:06:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private int idReserva;
     private int idCliente;
     private int idCoche;
     private Date fechaInicio;
     private Date fechaDevolucion;
     private Float precioTotal;
     private Float litros;

    public Reservas() {
    }

	
    public Reservas(int idReserva, int idCliente, int idCoche, Date fechaInicio, Date fechaDevolucion) {
        this.idReserva = idReserva;
        this.idCliente = idCliente;
        this.idCoche = idCoche;
        this.fechaInicio = fechaInicio;
        this.fechaDevolucion = fechaDevolucion;
    }
    public Reservas(int idReserva, int idCliente, int idCoche, Date fechaInicio, Date fechaDevolucion, Float precioTotal, Float litros) {
       this.idReserva = idReserva;
       this.idCliente = idCliente;
       this.idCoche = idCoche;
       this.fechaInicio = fechaInicio;
       this.fechaDevolucion = fechaDevolucion;
       this.precioTotal = precioTotal;
       this.litros = litros;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(int idCoche) {
        this.idCoche = idCoche;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Float getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Float precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Float getLitros() {
        return this.litros;
    }
    
    public void setLitros(Float litros) {
        this.litros = litros;
    }




}


